services:
  - type: web
    name: sistema-pets
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

  - type: postgres
    name: pets-database
    plan: free
    ipAllowList: []
